'use strict';

// Slim entrypoint generated by architecture/tools/split-gamejs-into-modules.js
// Keep plugin bridge and runtime boot order stable, while module definitions live in runtime/gamejs-modules/.
var globalObject = (function () { return this; })();
if (!globalObject && typeof GameGlobal !== "undefined") {
  globalObject = GameGlobal;
}

var pluginInfoMap = {};

globalObject.requirePlugin = globalObject.requirePlugin || function(path) {
  var position = path.indexOf("/");
  var alias = "";
  var pagePath = "";

  if (position !== -1) {
    alias = path.substr(0, position);
    pagePath = path.substr(position + 1, path.length);
  } else {
    alias = path;
  }

  if (Object.prototype.hasOwnProperty.call(pluginInfoMap, alias)) {
    if (pagePath.length === 0) {
      return require("__plugin__/" + pluginInfoMap[alias].appid);
    }
    return require("__plugin__/" + pluginInfoMap[alias].appid + "/" + pagePath);
  }

  console.error("not found alias: ", alias);
  throw new Error("Plugin " + alias + " is not defined.");
};

require("./runtime/gamejs-modules/manifest.js");
require("runtime/gamejs-modules/game.js");
