"use strict";

// Repacked by architecture/tools/repack-runtime-modules-from-source.js
// Source: source-project/runtime-modules/src/import-map.js
define("runtime/gamejs-modules/src/import-map.js", function (require, module, exports) {
  "use strict";

      // Auto-generated by architecture/tools/split-gamejs-into-modules.js
        Object.defineProperty(exports, "__esModule", { value: !0 }), (exports.default = void 0);
        exports.default = { imports: { cc: "./../cocos-js/cc.js" } };


});
