"use strict";

    // Auto-generated by architecture/tools/split-gamejs-into-modules.js
      var gameRuntimeBootstrap = require("../../architecture/boot/game-bootstrap.js");
      gameRuntimeBootstrap.bootGameRuntime(require);

