"use strict";

    // Auto-generated by architecture/tools/split-gamejs-into-modules.js
      Object.defineProperty(exports, "__esModule", { value: !0 }), (exports.default = void 0);
      exports.default = { imports: { cc: "./../cocos-js/cc.js" } };

