"use strict";

// Repacked by architecture/tools/repack-runtime-modules-from-source.js
// Source: source-project/runtime-modules/game.js
define("runtime/gamejs-modules/game.js", function (require, module, exports) {
  "use strict";

      // Auto-generated by architecture/tools/split-gamejs-into-modules.js
        var gameRuntimeBootstrap = require("../../architecture/boot/game-bootstrap.js");
        gameRuntimeBootstrap.bootGameRuntime(require);


});
