"use strict";

// Repacked by architecture/tools/repack-runtime-modules-from-source.js
// Source: source-project/runtime-modules/@babel/runtime/helpers/typeof.js
define("runtime/gamejs-modules/@babel/runtime/helpers/typeof.js", function (require, module, exports) {
  "use strict";

      // Auto-generated by architecture/tools/split-gamejs-into-modules.js
        function _typeof(o) {
          return (
            (module.exports = _typeof =
              "function" == typeof Symbol && "symbol" == typeof Symbol.iterator
                ? function (o) {
                    return typeof o;
                  }
                : function (o) {
                    return o && "function" == typeof Symbol && o.constructor === Symbol && o !== Symbol.prototype
                      ? "symbol"
                      : typeof o;
                  }),
            _typeof(o)
          );
        }
        module.exports = _typeof;


});
