"use strict";

// Repacked by architecture/tools/repack-runtime-modules-from-source.js
// Source: source-project/runtime-modules/assets/internal/index.js
define("runtime/gamejs-modules/assets/internal/index.js", function (require, module, exports) {
  "use strict";

      // Auto-generated by architecture/tools/split-gamejs-into-modules.js
        module.exports = require("./index.internal.js");


});
