"use strict";

// Repacked by architecture/tools/repack-runtime-modules-from-source.js
// Source: source-project/runtime-modules/@babel/runtime/helpers/Objectentries.js
define("runtime/gamejs-modules/@babel/runtime/helpers/Objectentries.js", function (require, module, exports) {
  "use strict";

      // Auto-generated by architecture/tools/split-gamejs-into-modules.js
        Object.entries ||
          (Object.entries = function (e) {
            for (var r = Object.keys(e), t = r.length, n = new Array(t); t--; ) n[t] = [r[t], e[r[t]]];
            return n;
          });


});
